/*
 * Product Catalog Management
 *
 * Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.  ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 5.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"time"
)

type ProductCatalogMvo struct {
	// List of root categories contained in this catalog
	Category []CategoryRefMvo `json:"category,omitempty"`
	// Description of this catalog
	Description string `json:"description,omitempty"`
	// Type of this Catalog, like Product, Service, Resource etc.
	CatalogType string `json:"catalogType,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
	// Catalog version
	Version string `json:"version,omitempty"`
	// List of parties involved in this catalog
	RelatedParty []RelatedPartyRefOrPartyRoleRefMvo `json:"relatedParty,omitempty"`
	// Date and time of the last update
	LastUpdate time.Time `json:"lastUpdate,omitempty"`
	// Used to indicate the current lifecycle status
	LifecycleStatus string `json:"lifecycleStatus,omitempty"`
	// Name of the catalog
	Name string `json:"name,omitempty"`
}
