/*
 * Product Catalog Management
 *
 * Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.  ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 5.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"time"
)

type ExportJob struct {
	// Data at which the job was completed
	CompletionDate time.Time `json:"completionDate,omitempty"`
	// The format of the exported data
	ContentType string `json:"contentType,omitempty"`
	// Date at which the job was created
	CreationDate time.Time `json:"creationDate,omitempty"`
	// Path to file or stream where errors encountered during the job processing can be written
	ErrorLog string `json:"errorLog,omitempty"`
	// URL of the root resource acting as the source for streaming content to the file specified by the export job
	Path string `json:"path,omitempty"`
	// Used to scope the exported data
	Query string `json:"query,omitempty"`

	Status *JobStateType `json:"status,omitempty"`
	// URL of the file containing the data to be exported
	Url string `json:"url,omitempty"`
	// unique identifier for export job
	Id string `json:"id,omitempty"`
	// Hyperlink reference
	Href           string `json:"href,omitempty"`
	Type           string `json:"@type,omitempty"`
	SchemaLocation string `json:"@schemaLocation,omitempty"`
	BaseType       string `json:"@baseType,omitempty"`
}
