/*
 * Product Catalog Management
 *
 * Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.  ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 5.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

import (
	"time"
)

type ProductSpecificationFvo struct {
	// The manufacturer or trademark of the specification
	Brand string `json:"brand,omitempty"`
	// A narrative that explains in detail what the product specification is
	Description string `json:"description,omitempty"`
	// isBundle determines whether a productSpecification represents a single productSpecification (false), or a bundle of productSpecification (true).
	IsBundle bool `json:"isBundle,omitempty"`
	// An identification number assigned to uniquely identity the specification
	ProductNumber string `json:"productNumber,omitempty"`
	// The category resource is used to group product specifications in logical containers. Categories can contain other categories and/or other catalog entries.
	Category []CategoryRefFvo `json:"category,omitempty"`

	ValidFor *TimePeriod `json:"validFor,omitempty"`
	// Product specification version
	Version string `json:"version,omitempty"`
	// A related party defines party or party role linked to a specific entity.
	RelatedParty []RelatedPartyRefOrPartyRoleRefFvo `json:"relatedParty,omitempty"`
	// A characteristic quality or distinctive feature of a ProductSpecification.  The characteristic can be take on a discrete value, such as color, can take on a range of values, (for example, sensitivity of 100-240 mV), or can be derived from a formula (for example, usage time (hrs) = 30 - talk time *3). Certain characteristics, such as color, may be configured during the ordering or some other process.
	ProductSpecCharacteristic []CharacteristicSpecificationFvo `json:"productSpecCharacteristic,omitempty"`
	// ServiceSpecification(s) required to realize a ProductSpecification.
	ServiceSpecification []ServiceSpecificationRefFvo `json:"serviceSpecification,omitempty"`
	// A type of ProductSpecification that belongs to a grouping of ProductSpecifications made available to the market. It inherits of all attributes of ProductSpecification.
	BundledProductSpecification []BundledProductSpecificationFvo `json:"bundledProductSpecification,omitempty"`
	// A migration, substitution, dependency or exclusivity relationship between/among product specifications.
	ProductSpecificationRelationship []ProductSpecificationRelationshipFvo `json:"productSpecificationRelationship,omitempty"`
	// The ResourceSpecification is required to realize a ProductSpecification.
	ResourceSpecification []ResourceSpecificationRefFvo `json:"resourceSpecification,omitempty"`
	// Complements the description of an element (for instance a product) through video, pictures...
	Attachment []AttachmentRefOrValueFvo `json:"attachment,omitempty"`
	// The Policy resource represents a policy/rule applied to ProductSpecification.
	Policy []PolicyRefFvo `json:"policy,omitempty"`

	TargetProductSchema *TargetProductSchemaFvo `json:"targetProductSchema,omitempty"`

	IntentSpecification *IntentSpecificationRefFvo `json:"intentSpecification,omitempty"`
	// Date and time of the last update
	LastUpdate time.Time `json:"lastUpdate"`
	// Used to indicate the current lifecycle status
	LifecycleStatus string `json:"lifecycleStatus"`
	// Name of the product specification
	Name string `json:"name"`
	// List of external identifieers for the specification, e.g. identifier in source catalog
	ExternalIdentifier []ExternalIdentifierFvo `json:"externalIdentifier,omitempty"`
	// unique identifier
	Id string `json:"id,omitempty"`
}
