/*
 * Product Catalog Management
 *
 * Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.  ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 5.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

// A base / value business entity used to represent money
type Money struct {
	// Currency (ISO4217 norm uses 3 letters to define the currency)
	Unit string `json:"unit,omitempty"`
	// A signed floating point number, the meaning of the sign is according to the context of the API that uses this Data type
	Value float32 `json:"value,omitempty"`
}
