/*
 * Product Catalog Management
 *
 * Product Catalog API is one of Catalog Management API Family. Product Catalog API goal is to provide a catalog of products.  ### Operations Product Catalog API performs the following operations on the resources : - Retrieve an entity or a collection of entities depending on filter criteria - Partial update of an entity (including updating rules) - Create an entity (including default values and creation rules) - Delete an entity - Manage notification of events
 *
 * API version: 5.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type BundledGroupProductOfferingMvo struct {
	// Locally unique identifier of the group, useful in case the parent product offering or group includes multiple groups.
	Id string `json:"id,omitempty"`
	// The name of the group of child offerings. Required to distinguish several choice groups.
	Name string `json:"name"`
	// Child offerings, from which instances can be created as direct or hierarchically indirect children of the parent offering.
	BundledProductOffering []BundledProductOfferingMvo `json:"bundledProductOffering,omitempty"`
	// Child groups of product offerings, to enable hierarchical sub-grouping.
	BundledGroupProductOffering []BundledGroupProductOfferingMvo `json:"bundledGroupProductOffering,omitempty"`

	BundledGroupProductOfferingOption *BundledGroupProductOfferingOptionMvo `json:"bundledGroupProductOfferingOption,omitempty"`
	// When sub-classing, this defines the sub-class Extensible name
	Type_ string `json:"@type"`
	// When sub-classing, this defines the super-class
	BaseType string `json:"@baseType,omitempty"`
	// A URI to a JSON-Schema file that defines additional attributes and relationships
	SchemaLocation string `json:"@schemaLocation,omitempty"`
}
